version: '3'

services:
  postgres:
    #container_name: postgres
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  nginx:
    #container_name: nginx
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    links:
      - postgres
  app:
    #container_name: app
    build: app/
